site_name: geolog

site_url: https://whitson-buck.github.io/geolog

repo_url: https://github.com/whitson-buck/geolog

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/whitson-buck/geolog/issues
    - API Reference:
          - geolog module: geolog.md
    - Examples:
        - examples/example.ipynb
        - examples/ipyleaflet.ipynb
        - examples/add_image.ipynb
        - examples/add_raster.ipynb
        - examples/basemap.ipynb
        - examples/add_csv_points.ipynb
        - examples/csv_to_shp.ipynb
